### ISSUE TITLE
New error 

### ISSUE THREAD

**Issue by jumperdos** [ethus3h/compiz-reloaded-overlay#6] opened 2020-02-12 06:54 UTC
> !!! The following installed packages are masked:
- dev-python/compizconfig-python-0.8.16::compiz-reloaded (masked by: invalid: DEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 11 in '/var/db/pkg/dev-python/compizconfig-python-0.8.16/DEPEND', invalid: RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 11 in '/var/db/pkg/dev-python/compizconfig-python-0.8.16/RDEPEND')
- x11-misc/ccsm-0.8.16::compiz-reloaded (masked by: invalid: RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 1 in '/var/db/pkg/x11-misc/ccsm-0.8.16/RDEPEND')
- x11-apps/fusion-icon-0.2.4-r1::compiz-reloaded (masked by: invalid: DEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 11 in '/var/db/pkg/x11-apps/fusion-icon-0.2.4-r1/DEPEND', invalid: RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 11 in '/var/db/pkg/x11-apps/fusion-icon-0.2.4-r1/RDEPEND')
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.

**Comment by jumperdos** [comment] 2020-02-13 19:22
Ah!!! , thanks for the overlay

**Comment by r7l** [comment] 2020-02-14 22:14
Having the same issue. Seems there have been some changes due to Python 2 deprecation. Is there still hope for this version of Compiz?

**Comment by r7l** [comment] 2020-02-15 12:31
Just checked the Compiz Reloaded project and it seems to active.

**Comment by kdudka** [comment] 2020-02-26 13:42
This error seems to be caused by the following change in Gentoo:

https://blogs.gentoo.org/mgorny/2020/02/10/no-more-python_targets-in-single-r1/

**Comment by reppkchen** [comment] 2020-03-05 00:09
I really need Compiz!  Wish this problem could be resolved.

**Comment by kdudka** [comment] 2020-03-05 08:09
Luckily, this seems to be a minor packaging issue, not a code-related issue.  I have not yet convinced myself to have a look at it because the previously built packages are still working for me...

**Comment by ghost** [comment] 2020-03-10 19:35
Using the ebuilds provided in a manually created repo fixes the issue. Definitely just a packaging bug.  Hope the pull request gets accepted soon.

**Comment by ethus3h** [comment] 2020-03-11 11:20
Really sorry for the delay! Thanks @kdudka for the merge request; merged — I need to run for now; will return to this in a bit to see about giving the live ebuilds the same treatment. Also added a link to a Matrix chat to the readme, in case I need prodding like this again (I try to check Matrix daily or so, while I haven't been so good about checking this regularly, as it turned out — sorry again)... Thanks again all.

**Comment by kdudka** [comment] 2020-03-11 11:35
No problem at all.  Thank you for maintaining this overlay!

**Comment by ethus3h** [comment] 2020-05-09 19:03
I think these are all cleaned up; if you have issues show up still please feel free to post a new issue or re-open this one (can people other than me re-open an issue? I don't know...).

Thank you again for the report and comments, and sorry for the delay!

**Closed as completed by ethus3h** 2020-05-09 19:03 UTC
